

tags = ["blog", "responsive", "minimal", "dark", "light", "multilingual"]
features = ["blog", "sass", "dark"]

min_version = "0.87.0"

# If the theme has a single author
[author]
    name = "Mohamed Abdullah"
    homepage = "https://mdxabu.com"
